@startuml
actor Student

Student -> Key : acquire() \nwait to enter
Student -> WashingMachine : acquire() \nwait to start washing

Student -> Student : decide_to_exit() (70% chance, if N - 1 > resting students)
alt decides to exit
    Key -> Student : release() \nleaves laundromat and nr. of resting students increases
    Student -> Key : acquire() \nre-enters and nr. of resting students decreases
end

Student -> Student : wash()

WashingMachine -> Student : release() \ndone washing
Student -> Dryer : acquire() \nwait to start drying

Student -> Student : decide_to_exit() (70% chance, if N - 1 > resting students)
alt decides to exit
    Key -> Student : release() \nleaves laundromat and nr. of resting students increases
    Student -> Key : acquire() \nre-enters and nr. of resting students decreases
end

Student -> Student : dry()

Dryer -> Student : release() \ndone drying
Key -> Student: release() \nexits laundromat

@enduml
