[package]
name = "research"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
json = "0.12.4"
rand = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
